#默认使用配置
spring:
  profiles:
    active: dev

#整合mybatis
mybatis:
  typeAliasesPackage: com.stopcar.pojo
  mapperLocations: classpath:mapper/*.xml
---
#开发配置
spring:
  profiles:
    active: dev
  #jdbc连接数据库
  datasource:
    url: jdbc:mysql://localhost:3306/ticket_project?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 176624122
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    open-in-view: false
  #更改端口号
server:
  port: 8080
  spring:
    thymeleaf:
      prefix: classpath:/templates/
      mode: html5
      encoding: utf-8
      suffix: .html